### ISSUE TITLE
suggest to make frontend into two different repos

### ISSUE THREAD

**Issue by PirateCode-eth** [ForeverPFP/primary-pfp-frontend#19]
one for PrimaryPFP.org, one for Forever PFP(tmp name).

let's finish PrimaryPFP first, would be a small step, easier, what do you think @0xtiby

**Comment by 0xtiby** [comment]
So I create a new one name PrimaryPFP.  With only the step by step to set Primary pfp ?

**Comment by PirateCode-eth** [comment]
Yes, and we can make a develop menu for devs easy to use primary PFP data onchain, and we can try to add it into wagmi.sh.

**Comment by PirateCode-eth** [comment]
> So I create a new one named PrimaryPFP.  With only the step by step to set Primary pfp ? 

I google the best repo naming convention, looks like primary-PFP-frontend is a better name?

https://github.com/bcgov/BC-Policy-Framework-For-GitHub/blob/master/BC-Gov-Org-HowTo/Naming-Repos.md

**Comment by PirateCode-eth** [comment]
I would like to suggest this repo is only for website of ForeverPFP which will build on many different projects: https://github.com/ForeverPFP/.github/blob/main/profile/README.md

and make primary PFP one of the components.

**Comment by 0xtiby** [comment]
Ok let's do this.

**Comment by 0xtiby** [comment]
@PirateCode-eth I'm almost done with the step by step view. After finish it and merged I will rework and rename this repo to be the PrimaryPFP repo.

**Comment by PirateCode-eth** [comment]
Cool.
