### ISSUE TITLE
how about to make query community twitter accounts first

### ISSUE THREAD

**Issue by 0xtiby** [ForeverPFP/primary-pfp-frontend#4]
Recap of the discussion before moving it here

<div type='discussions-op-text'>

<sup>Originally posted by **PirateCode-eth** April  5, 2023</sup>
I think it won't be hard to bind/delegate by etherscan.io. Maybe we can do query community twitter accounts first?

Maybe need subgraph thing for that. What do you think? @0xtiby </div>

<div type='discussions-op-text'>

<sup>Originally posted by **PirateCode-eth** April  5, 2023</sup>
As you want I think it won't take to much time to bind delegate on website. Have you an idea on how to query community accounts ?</div>

<div type='discussions-op-text'>

<sup>Originally posted by **Tiby** April  5, 2023</sup>
 It need subgraph to help finish this function from the event of the contract:
 
 1. these three events help we know, what PFP is bound to a collection by the community members now: https://github.com/ForeverPFP/ForeverPFP/blob/main/src/IPFPBinding.sol#L15
 2. by those bind address we can find the primary ENS
 3. find the twitter account in the ENS content:
 
![image](https://user-images.githubusercontent.com/101003754/230709053-32390e19-6b1f-4b8b-a210-e04e556aac06.png)

</div>

**Comment by 0xtiby** [comment]
@PirateCode-eth  I think we can closed this one ?

**Comment by PirateCode-eth** [comment]
yes, it can be done by this function: https://github.com/ForeverPFP/primary-pfp-contract/blob/main/src/IPrimaryPFP.sol#L126
