### ISSUE TITLE
Testnet and Mainnet

### ISSUE THREAD

**Issue by 0xtiby** [ForeverPFP/primary-pfp-frontend#6]
I build the app to only accept one network at time. The two networks allowed are Goerli and Mainnet and it configurable via environment variables. 

I was thinking of deploying two version : 
- Goerlie : testnet.foreverpfp.xyz/
- Mainnet : foreverpfp.xyz/

What do you think of that @PirateCode-eth

**Comment by PirateCode-eth** [comment]
For sure, testnet first :)

**Comment by 0xtiby** [comment]
Should I deploy the website on my side and you create the dns record on your side. Or you want to setup the hosting too.

**Comment by PirateCode-eth** [comment]
I can create the dns record.

**Comment by 0xtiby** [comment]
I tried to deploy on vercel but as the repo is in organization we should use a team plan. Do you have one ?

**Comment by PirateCode-eth** [comment]
Team for GitHub or team for vercel?

**Comment by 0xtiby** [comment]
Team plan for vercel.  The "problem" is that it's 20$/month/user. If you don't have it and don't want to manage it I can pay for one user (me).  But the only thing is to deliver as quick as possible to avoid paying for nothing :blush:

**Comment by PirateCode-eth** [comment]
https://testnet.PrimaryPFP.org, it's done.
